# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dd34dd3cada9c49f517921aa251b40c0b9296a2fbe7e36a698abd8901c472a685ade722b9b6b0037e50e949e1861c6ee1a62a6253b466ffa61999ade58c4b7c

test:
  secret_key_base: d6b307107b1b786fa5bb7a04bb1e242ada8f6205d49a6216c0dd4c72a6e058979f29a63d92514db81ad80318dcc75b89dc46f364cffc60992c3105d9f45fa940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
